sudo: false
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
script:
  - "prove -lrv t"
notifications:
  email:
    recipients:
      - vikas@cpan.org
    on_success: always
    on_failure: alway
